---
AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Create Secrets Manager protected secrets

Parameters:
  Var1:
    Description: Say something
    Type: String
    Default: ""
  Var2:
    Description: Say something
    Type: String
    Default: ""

Resources:
  SecretA:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Var1}-${Var2}-SecretA'
      Description: Secret with a dynamically generated password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "root"}'
        GenerateStringKey: "password"
        PasswordLength: 40
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: AppA

## Example with hardcoded password
#  SecretB:
#    Type: AWS::SecretsManager::Secret
#    Properties:
#      Name: !Sub '${Var1}-${Var2}-SecretB'
#      Description: Secret with a hardcoded password
#      SecretString: '{"username":"root","password":"super-duper-secret-password"}'
#      Tags:
#        - Key: AppName
#          Value: AppB

## How to retrieve the secret
#       {{resolve:secretsmanager:secret-id:secret-string:json-key:version-stage:version-id}}
# !Sub "{{resolve:secretsmanager:${Var1}-${Var2}-SecretA:SecretString:username}}"
# !Sub "{{resolve:secretsmanager:${Var1}-${Var2}-SecretA:SecretString:password}}"